import xml.etree.ElementTree as ElementTree
import sys            

cpuNameTable = {
    "CM0+": "cortex-m0plus",
    "CM0": "cortex-m0",
    "CM0PLUS": "cortex-mplus",
    "CM1": "cortex-m1",
    "CM3": "cortex-m3",
    "CM4": "cortex-m4",
    "CM7": "cortex-m7"
}

for svd in sys.argv[1:]:
    tree = ElementTree.parse(svd)
    root = tree.getroot()
    deviceName = tree.find("name").text

    # create cmake file
    with open("{}.cmake".format(deviceName), 'w') as f:
        cpu = root.find("cpu")
        if cpu is not None:
            name = cpu.find("name")
            if name is not None: 
                text = name.text
                f.write("set(SVD_CPU {})\n".format(cpuNameTable[text]))
        
            endian = cpu.find("endian")
            if endian is not None:
                text = endian.text
                f.write("set(SVD_ENDIAN {})\n".format(text))
            
            fpuPresent = cpu.find("fpuPresent")
            if fpuPresent is not None:
                text = fpuPresent.text
                value = ""
                if text == "false" or text == "0":
                    value = "soft"
                elif text == "true" or text == "1":
                    value = "hard"

                if value != "":
                    f.write("set(SVD_FLOAT_ABI {})\n".format(value))

    # create header file
    with open("{}.hpp".format(deviceName), 'w') as f:
        interrupts = {}
        print(deviceName)
        f.write("// This is a file generated by svd-alias.\n\n")
        f.write("#pragma once\n\n")
        f.write("#include \"svd-alias/bit-field.hpp\"\n")
        f.write("#include \"svd-alias/register.hpp\"\n\n")
        f.write('struct %s {\n' % deviceName)
        for peripheral in root.iter("peripheral"):
            peripheralName = peripheral.find("name").text
            baseAddress = int(peripheral.find("baseAddress").text, 16)
            print("\t{}: {}".format(peripheralName, hex(baseAddress)))

            for interrupt in peripheral.iter("interrupt"):
                interrupts[interrupt.find("value").text] = interrupt.find("name").text
            
            
            if peripheral.attrib and peripheral.attrib["derivedFrom"]:
                for tmp in root.iter("peripheral"):
                    if peripheral.attrib["derivedFrom"] == tmp.find("name").text:
                        peripheral = tmp
                        break

            if peripheral.find("description") is not None:
                peripheralDescription = peripheral.find("description").text
                f.write('    // %s\n' % ' '.join(peripheralDescription.replace('\n', ' ').replace('\r', '').split()))
            
            f.write('    struct %s {\n' % peripheralName)
            for register in peripheral.iter("register"):
                registerName = register.find("name").text
                addressOffset = int(register.find("addressOffset").text, 16)
                if register.find("description") is not None:
                    registerDescription = register.find("description").text
                    f.write('        // %s\n' % ' '.join(registerDescription.replace('\n', ' ').replace('\r', '').split()))
                
                f.write('        struct %s : public Register<%s> {\n' % (registerName, hex(baseAddress + addressOffset)))
                for field in register.iter("field"):
                    fieldDescription = field.find("description");
                    fieldName = field.find("name").text
                    bitWidth = field.find("bitWidth").text
                    bitOffset = field.find("bitOffset").text
                    f.write('            using %s = Field<%s, %s>;' % (fieldName if fieldName != registerName else "Field", bitOffset, bitWidth))
                    if fieldDescription is not None:
                        f.write('    // %s' % ' '.join(fieldDescription.text.replace('\n', ' ').replace('\r', '').split()))
                    
                    f.write('\n')

                f.write('        };\n\n')

            f.write('    };\n\n')
        
        for number, interrupt in interrupts.items():
            print(number, interrupt)

        f.write('};\n')



    
